# load packages

library(tidyverse)
library(dplyr)
library(ggplot2)
library(readxl)
library(plotly)
library(ggthemes)
library(paletteer)
library(nord)
library(data.table)

# define colour palettes

col_palette <- c(nord("frost")[2],
                 nord("mountain_forms")[1],
                 nord("aurora")[4],
                 nord("aurora")[1],
                 nord("moose_pond")[3])

col_palette2 <- c(nord("mountain_forms")[1],
                  nord("victory_bonds")[2],
                  nord("aurora")[2],
                  nord("aurora")[3],
                  nord("aurora")[5],
                  nord("aurora")[4],
                  nord("frost")[2],
                  nord("moose_pond")[3],
                  nord("silver_mine")[2],
                  nord("aurora")[6],
                  nord("victory_bonds")[3])

# covariance matrix generated by PCAngsd
cov <- as.matrix(read.table("files/WBD_GLs_PCAngsd.cov"))

# metadata including ID, pop assignments broad and fine
Region <- read.table("file_lists/pop_file_broad_fine.info",as.is = T)

e <- eigen(cov)

pc <- e$vectors[,1:2]
pc2 <- e$vectors[,1:3]
pca <- as.data.frame(pc)
pca2 <- as.data.frame(pc2)
pca_pop <- cbind(pca, Region)
pca_pop2 <- cbind(pca2, Region)
colnames(pca_pop) <- c("PC1", "PC2", "ID", "POP", "Region","POP2")
colnames(pca_pop2) <- c("PC1", "PC2", "PC3", "ID", "POP", "Region","POP2")

POP <- as.factor(Region$V2)
Region <- as.factor(Region$V3)

pca.eigenval.sum = sum(e$values) #sum of eigenvalues

# percentage of variance for the first four axes
varPC1 <- (e$values[1]/pca.eigenval.sum)*100
VarPc2 <- (e$values[2]/pca.eigenval.sum)*100
VarPC3 <- (e$values[3]/pca.eigenval.sum)*100
VarPC4 <- (e$values[4]/pca.eigenval.sum)*100

# PCA with broad pop assignments

(PCA_plot_broad1 <- ggplot(pca_pop) +
    aes(x = PC1, y = PC2, col=POP2) +
    scale_color_manual(values = col_palette) +
    geom_point(size = 8, alpha = 0.6, stroke = 0.12) +
    xlab(paste0("PC1 ", "(", round((e$values[1]/pca.eigenval.sum)*100), "%)")) +
    ylab(paste0("PC2 ", "(", round((e$values[2]/pca.eigenval.sum)*100), "%)")) +
    #stat_ellipse() +
    #labs(title = "B") +
    theme_classic())

# PCA (2&3) with broad pop assignments

(PCA_plot_broad2 <- ggplot(pca_pop2) +
    aes(x = PC2, y = PC3, col=POP2) +
    scale_color_manual(values = col_palette) +
    geom_point(size = 8, alpha = 0.6, stroke = 0.12) +
    xlab(paste0("PC2 ", "(", round((e$values[1]/pca.eigenval.sum)*100), "%)")) +
    ylab(paste0("PC3 ", "(", round((e$values[2]/pca.eigenval.sum)*100), "%)")) +
    #stat_ellipse() +
    #labs(title = "B") +
    theme_classic())

# PCA with fine pop assignments

(PCA_plot_fine1 <- ggplot(pca_pop) +
    aes(x = PC1, y = PC2, col=Region) +
    scale_color_manual(values = col_palette2) +
    geom_point(shape = 19, size = 8, alpha = 0.7, stroke = 0.15) +
    xlab(paste0("PC1 ", "(", round((e$values[1]/pca.eigenval.sum)*100), "%)")) +
    ylab(paste0("PC2 ", "(", round((e$values[2]/pca.eigenval.sum)*100), "%)")) +
    #stat_ellipse() +
    #labs(title = "B") +
    theme_classic())

# Just males

cov_males <- as.matrix(read.table("files/WBD_GLs_PCAngsd_males.cov"))

Region_males <- read.table("file_lists/pop_file_males.info",as.is = T)

e_males <- eigen(cov_males)

pc_males <- e_males$vectors[,1:2]
pc2_males <- e_males$vectors[,1:3]
pca_males <- as.data.frame(pc_males)
pca2_males <- as.data.frame(pc2_males)
pca_pop_males <- cbind(pca_males, Region_males)
pca_pop2_males <- cbind(pca2_males, Region_males)
colnames(pca_pop_males) <- c("PC1", "PC2", "Region")
colnames(pca_pop2_males) <- c("PC1", "PC2", "PC3", "Region")

pca.eigenval.sum_males = sum(e$values) #sum of eigenvalues

varPC1_males <- (e_males$values[1]/pca.eigenval.sum_males)*100
VarPc2_males <- (e_males$values[2]/pca.eigenval.sum_males)*100
VarPC3_males <- (e_males$values[3]/pca.eigenval.sum_males)*100
VarPC4_males <- (e_males$values[4]/pca.eigenval.sum_males)*100

(PCA_plot_males <- ggplot(pca_pop_males) +
    aes(x = PC1, y = PC2, col=Region) +
    scale_color_manual(values = col_palette2) +
    geom_point(size = 8, alpha = 0.8, stroke = 1.1) +
    xlab(paste0("PC1 ", "(", round((e_males$values[1]/pca.eigenval.sum_males)*100), "%)")) +
    ylab(paste0("PC2 ", "(", round((e_males$values[2]/pca.eigenval.sum_males)*100), "%)")) +
    #stat_ellipse() +
    #labs(title = "B") +
    theme_classic())

(PCA_plot_males2 <- ggplot(pca_pop2_males) +
    aes(x = PC2, y = PC3, col=Region) +
    scale_color_manual(values = col_palette2) +
    geom_point(size = 8, alpha = 0.8, stroke = 1.1) +
    xlab(paste0("PC2 ", "(", round((e_males$values[1]/pca.eigenval.sum_males)*100), "%)")) +
    ylab(paste0("PC3 ", "(", round((e_males$values[2]/pca.eigenval.sum_males)*100), "%)")) +
    #stat_ellipse() +
    #labs(title = "B") +
    theme_classic())


# Just females

cov_females <- as.matrix(read.table("files/WBD_GLs_PCAngsd_females.cov"))

Region_females <- read.table("file_lists/pop_file_females.info",as.is = T)

e_females <- eigen(cov_females)

pc_females <- e_females$vectors[,1:2]
pc2_females <- e_females$vectors[,1:3]
pca_females <- as.data.frame(pc_females)
pca2_females <- as.data.frame(pc2_females)
pca_pop_females <- cbind(pca_females, Region_females)
pca_pop2_females <- cbind(pca2_females, Region_females)
colnames(pca_pop_females) <- c("PC1", "PC2", "Region")
colnames(pca_pop2_females) <- c("PC1", "PC2", "PC3", "Region")

pca.eigenval.sum_females = sum(e$values) #sum of eigenvalues

varPC1_females <- (e_females$values[1]/pca.eigenval.sum_females)*100
VarPc2_females <- (e_females$values[2]/pca.eigenval.sum_females)*100
VarPC3_females <- (e_females$values[3]/pca.eigenval.sum_females)*100
VarPC4_females <- (e_females$values[4]/pca.eigenval.sum_females)*100

(PCA_plot_females <- ggplot(pca_pop_females) +
    aes(x = PC1, y = PC2, col=Region) +
    scale_color_manual(values = col_palette2) +
    geom_point(size = 8, alpha = 0.8, stroke = 1.1) +
    xlab(paste0("PC1 ", "(", round((e_females$values[1]/pca.eigenval.sum_females)*100), "%)")) +
    ylab(paste0("PC2 ", "(", round((e_females$values[2]/pca.eigenval.sum_females)*100), "%)")) +
    #stat_ellipse() +
    #labs(title = "B") +
    theme_classic())

(PCA_plot_females2 <- ggplot(pca_pop2_females) +
    aes(x = PC2, y = PC3, col=Region) +
    scale_color_manual(values = col_palette2) +
    geom_point(size = 8, alpha = 0.8, stroke = 1.1) +
    xlab(paste0("PC2 ", "(", round((e_females$values[1]/pca.eigenval.sum_females)*100), "%)")) +
    ylab(paste0("PC3 ", "(", round((e_females$values[2]/pca.eigenval.sum_females)*100), "%)")) +
    #stat_ellipse() +
    #labs(title = "B") +
    theme_classic())

# save figures

ggsave("figures/Figure_1b.pdf", PCA_plot_broad1, height = 16.5, width = 21, units = "cm")
ggsave("figures/Figure_S6.pdf", PCA_plot_broad2, height = 16.5, width = 21, units = "cm")
ggsave("figures/Figure_x.pdf", PCA_plot_fine1, height = 16.5, width = 21, units = "cm")
ggsave("figures/Figure_S7a.pdf", PCA_plot_males, height = 16.5, width = 21, units = "cm")
ggsave("figures/Figure_S7a_2.pdf", PCA_plot_males2, height = 16.5, width = 21, units = "cm")
ggsave("figures/Figure_S7b.pdf", PCA_plot_females, height = 16.5, width = 21, units = "cm")
ggsave("figures/Figure_S7b_b.pdf", PCA_plot_females2, height = 16.5, width = 21, units = "cm")
